# Generated by Django 4.1.7 on 2023-03-20 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0002_alter_usabilitytest_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250, null=True)),
                ('timestamp', models.TimeField(null=True)),
                ('usability_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='theater.usabilitytest')),
            ],
        ),
    ]
