# Generated by Django 4.1.7 on 2023-03-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0003_testnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usabilitytestvideo',
            name='file',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
