# Generated by Django 4.1.7 on 2023-03-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0004_usabilitytestvideo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usabilitytestvideo',
            name='file',
            field=models.FileField(null=True, upload_to='media/theater/', verbose_name=''),
        ),
    ]
