# Generated by Django 4.1.7 on 2023-03-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0005_alter_usabilitytestvideo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testnotes',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
