# Generated by Django 4.1.7 on 2023-03-24 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0008_alter_usabilitytestvideo_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utterances', models.TextField()),
                ('usability_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='theater.usabilitytest')),
            ],
        ),
    ]
