# Generated by Django 4.1.7 on 2023-03-26 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0009_transcript'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('confidence', models.FloatField()),
                ('speaker', models.CharField(max_length=50)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='theater.transcript')),
            ],
        ),
    ]
