# Generated by Django 4.1.7 on 2023-03-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0010_sentimentanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentanalysis',
            name='sentiment',
            field=models.CharField(default='neutral', max_length=100),
            preserve_default=False,
        ),
    ]
